FROM node:latest
LABEL maintainer=jon@jaggersoft.com
LABEL maintainer=marcoemrich77@googlemail.com

RUN mkdir /etc/rescript
WORKDIR /etc/rescript
COPY . .
RUN npm install && chown -R . sandbox

COPY red_amber_green.rb /usr/local/bin
