FROM cyberdojofoundation/javascript-node:f77006d
LABEL maintainer=jon@jaggersoft.com
LABEL maintainer=?????

RUN mkdir /etc/ts
WORKDIR /etc/ts
COPY package.json .
RUN npm install

COPY red_amber_green.rb /usr/local/bin
