FROM node:latest
LABEL maintainer=jon@jaggersoft.com
LABEL maintainer=marcoemrich77@googlemail.com

RUN mkdir /etc/rescript
WORKDIR /etc/rescript
COPY package.json .
RUN npm install

COPY red_amber_green.rb /usr/local/bin
